# src_dir: /home/physics_atv/workspace/datasets/irl_postproc
# dst_dir: /home/physics_atv/workspace/datasets/irl_postpostproc
src_dir: /home/physics_atv/ssd/big_irl_dataset
dst_dir: /home/physics_atv/ssd/big_irl_dataset_postproc
save_every: 20 #add every n-th frame

H: 100
dt: 0.1

#data folders
cmd: cmd
steer_angle: steer_angle
odom: odom
gps_odom: gps_odom
local_gridmap: local_gridmap
local_dino_map: local_dino_map
local_vlad_map: local_vlad_map
local_semantic_map: local_semantic_map
pcl: pcl
img: image_left_color
