primitives:
    L: 4.0

#    linear_resolution: 1.0
#    angular_discretization: 16
#    maxdist: 5.

    linear_resolution: 1.0
    angular_discretization: 32
    maxdist: 4.0

    angular_weight: 1.

state_lattice:
    length_x: 120.
    length_y: 120.
    origin: [-60., -60.]

costmap:
    length_x: 120.
    length_y: 120.
    resolution: 0.5
    origin: [-60., -60.]
