src_dir: /media/striest/aaa/2025_irl_kitti/train
dst_dir: /media/striest/aaa/2025_irl
save_every: 20 #add every n-th frame
min_avg_speed: 1.0 #dont use samples below this average speed

H: 75
dt: 0.1

#data folders
cmd: cmd
steer_angle: steer_angle
odom: odometry
gps_odom: gps_odom
local_gridmap: bev_map_reduce
pcl: pointcloud_in_odom
img: image
