src_dir: /home/tartandriver/workspace/datasets/irl_postproc
dst_dir: /home/tartandriver/workspace/datasets/irl_postpostproc3
save_every: 20 #add every n-th frame

H: 100
dt: 0.1

#data folders
cmd: cmd
steer_angle: steer_angle
odom: odom
gps_odom: gps_odom
local_gridmap: local_gridmap
local_dino_map: local_dino_map
pcl: pcl
img: image_left_color
