src_dir: /media/striest/sam_ssd_2/rr_kitti/
dst_dir: /home/tartandriver/workspace/datasets/2025_irl_data_rr
save_every: 20 #add every n-th frame
min_avg_speed: 1.0 #dont use samples below this average speed

H: 75
dt: 0.1

#data folders
cmd: cmd
steer_angle: steer_angle
odom: odom
gps_odom: gps_odom
local_gridmap: vfm_gridmap
pcl: super_odometry_pc
img: image_left_color
