src_dir: /home/tartandriver/workspace/datasets/2025_irl_kitti
dst_dir: /home/tartandriver/workspace/datasets/2025_irl_data
save_every: 20 #add every n-th frame

H: 100
dt: 0.1

#data folders
cmd: cmd
steer_angle: steer_angle
odom: odom
gps_odom: gps_odom
local_gridmap: vfm_gridmap
pcl: super_odometry_pc
img: image_left_color
