experiment:
    save_to: /home/tartandriver/workspace/experiments/yamaha_irl_dino/
    name: debug_voxel_irl
    device: cuda
    epochs: 50
    steps_per_epoch: 100
    save_every: 1

footprint:
    params:
        length: 4.0
        width: 2.0
          
        #displacement to get to the center of the footprint from the center of the rear axle
        length_offset: 1.2
        width_offset: 0.0
        
        nl: 25
        nw: 15

algo:
    type: VoxelMPPIIRL
    params:
        batch_size: 4
        reg_coeff: 0.0000001
        # reg_coeff: 0.0
        speed_coeff: 1.0 #turn off speedmaps for now
        grad_clip: 10.0

dataset:
    type: VoxelIRLDataset
    params:
        root_fp: /media/striest/offroad/datasets/irl_kitti
        device: cuda

        H: 75
        sample_every: 20
        min_avg_speed: 1.0

network:
    type: VoxelResnetCategorical
    params:
        voxel_params:
            hidden_channels: [64, 64, 64]
            hidden_activation: tanh
            hidden_kernel_size: 3

        resnet_params:
            speed_nbins: 15
            max_speed: 15.
            cost_nbins: 20
            max_cost: 4.

            hidden_channels: [64,]
            hidden_activation: tanh
            hidden_kernel_size: 5
            dropout: 0.0

netopt:
    type: Adam
    params: {}

solver:
    type: mpc
    mpc_fp: /home/tartandriver/tartandriver_ws/src/planning/maxent_irl_maps/config/mpc/throttle_mppi.yaml

metrics:
