experiment:
    save_to: /home/tartandriver/workspace/experiments/yamaha_irl_dino/
    name: tc_debug_linear_visual_feats
    device: cuda
    epochs: 10
    steps_per_epoch: 900
    save_every: 1

footprint:
    params:
        length: 5.0
        width: 3.0
        length_offset: -1.0
        width_offset: 0.0
        nl: 25
        nw: 25

torch_coordinator_config: '/home/tartandriver/tartandriver_ws/src/planning/maxent_irl_maps/config/torch_coordinator/coordinator_config.yaml'

algo:
    type: MPPIIRLSpeedmapsTorchCoordinator
    params:
        batch_size: 1
        reg_coeff: 0.0
        speed_coeff: 1.0
        grad_clip: 10.0
        mppi_itrs: 5

dataset:
    type: VoxelMappingMaxEntIRLDataset
    params:
        root_fp: /media/striest/aaa/2025_irl_kitti
        device: cuda
        H: 75

#TODO initialize the BEV and visual nets here
network:
    type: ResnetCategorical
    params:
        speed_nbins: 15
        max_speed: 15.
        cost_nbins: 20
        max_cost: 10.
        hidden_channels: [128, 128]
        hidden_activation: tanh
        hidden_kernel_size: 5
        dropout: 0.0

netopt:
    type: Adam
    params: {}

solver:
    type: mpc
    mpc_fp: /home/tartandriver/tartandriver_ws/src/planning/maxent_irl_maps/config/mpc/throttle_mppi.yaml

metrics:
