experiment:
    save_to: /home/tartandriver/workspace/experiments/yamaha_irl_dino/no_svd_debug
    name: dino_pca_diff_unk
    device: cuda
    epochs: 5
    steps_per_epoch: -1
    save_every: 1

footprint:
    params:
        length: 4.0
        width: 2.0
        length_offset: -1.0
        width_offset: 0.0
        nl: 15
        nw: 15

algo:
    type: MPPIIRLSpeedmaps
    params:
        batch_size: 4
        reg_coeff: 1.0e-08
        speed_coeff: 1.0 #turn off speedmaps for now
        grad_clip: 1.0

dataset:
    type: MaxEntIRLDataset
    params:
        root_fp: /home/tartandriver/workspace/datasets/irl_postpostproc_multimap/train
        device: cuda
        feature_keys:
            # DINO
            - dino_0
            - dino_1
            - dino_2
            - dino_3
            - dino_4
            - dino_5
            - dino_6
            - dino_7
            - dino_8
            - dino_9
            - dino_10
            - dino_11
            - dino_12
            - dino_13
            - dino_14
            - dino_15

            # geom
            - diff
            - unknown

            # - terrain
            # - terrain_slope

            # - SVD1
            # - SVD2
            # - SVD3
            # - roughness

network:
    type: ResnetCategorical
    params:
        cost_nbins: 20
        max_cost: 10.
        speed_nbins: 30
        max_speed: 15.
        hidden_channels: [128, 128]
        hidden_activation: relu
        dropout: 0.0

netopt:
    type: Adam
    params: {}

solver:
    type: mpc
    mpc_fp: /home/tartandriver/tartandriver_ws/src/planning/maxent_irl_maps/config/mpc/throttle_mppi.yaml

metrics:
