experiment:
    save_to: /home/tartandriver/workspace/experiments/yamaha_irl_dino/
    name: dinob_reg_gascola_categorical_log_cost_no_reg
    device: cuda
    epochs: 10
    steps_per_epoch: -1
    save_every: 1

footprint:
    params:
        length: 5.0
        width: 3.0
        length_offset: -0.5
        width_offset: 0.0
        nl: 25
        nw: 25

algo:
    type: MPPIIRLSpeedmaps
    params:
        batch_size: 4
        reg_coeff: 0.0
        speed_coeff: 1.0 #turn off speedmaps for now
        grad_clip: 10.0

dataset:
    type: MaxEntIRLDataset
    params:
        root_fp: /home/tartandriver/workspace/datasets/2025_irl_data/test
        device: cuda
        feature_keys:
            # VFM
            - dino_0
            - dino_1
            - dino_2
            - dino_3
            - dino_4
            - dino_5
            - dino_6
            - dino_7
            - dino_8
            - dino_9
            - dino_10
            - dino_11
            - dino_12
            - dino_13
            - dino_14
            - dino_15

            # geom
            - min_elevation
            - max_elevation
            - num_voxels
            - terrain
            - slope
            - diff

network:
    type: ResnetCategorical
    params:
        speed_nbins: 15
        max_speed: 15.
        cost_nbins: 20
        max_cost: 10.
        hidden_channels: [128, 128]
        hidden_activation: tanh
        hidden_kernel_size: 5
        dropout: 0.0

netopt:
    type: Adam
    params: {}

solver:
    type: mpc
    mpc_fp: /home/tartandriver/tartandriver_ws/src/planning/maxent_irl_maps/config/mpc/throttle_mppi.yaml

metrics:
