experiment:
    save_to: /home/atv/Desktop/experiments/yamaha_maxent_irl/
    name: arl_sim_2layer_resnet_adamw_001_nopos
    device: cuda
    epochs: 20
    steps_per_epoch: -1
    save_every: 1

algo:
    type: MPPIIRLSpeedmaps
    params:
        mppi_itrs: 10
        batch_size: 12
        reg_coeff: 1.0e-08
        speed_coeff: 0.0
        grad_clip: 1.0

dataset:
    type: MaxEntIRLDataset
    params:
        bag_fp: /home/atv/Desktop/datasets/warthog_simulation_maxent_irl/rosbags_train
        preprocess_fp: /home/atv/Desktop/datasets/yamaha_maxent_irl/big_gridmaps/torch_train
        map_features_topic: /local_gridmap
        odom_topic: /warty/odom
        image_topic: /warty/forward/image/compressed
        horizon: 75
        feature_keys:
            - height_low
            - height_mean
            - height_high
            - height_max
            - diff
            - terrain
            - terrain_slope
            - roughness
            - SVD1
            - SVD2
            - SVD3
            - unknown
            - ego_speed

network:
    type: ResnetCostmapSpeedmapCNNEnsemble2
    params:
        ensemble_dim: 1
        hidden_channels: [16, ]
        hidden_activation: relu
        activation_type: none
        activation_scale: 1.0
        dropout: 0.2

netopt:
    type: AdamW
    params: {}

cost_function:
    terms:
        - type: CostmapProjection
          weight: 1.0
          params:

        - type: EuclideanDistanceToGoal
          weight: 10.0
          params:

model:
    type: SkidSteer
    params:
        v_lim: [2.0, 5.0]
        w_lim: [-1.0, 1.0]

trajopt:
    type: BatchMPPI
    params: 
        num_samples: 2048
        control_params:
            sys_noise: [2.0, 1.0]
            temperature: 0.02
            use_ou: True
            ou_alpha: 0.9
            ou_scale: 10.0
            d_ou_scale: 5.0

metrics:
