experiment:
    save_to: /home/atv/Desktop/experiments/yamaha_maxent_irl/202311_baselines
    name: threelayer_resnet
    device: cuda
    epochs: 10
    steps_per_epoch: 100
    save_every: 1

footprint:
    params:
        length: 5.0
        width: 3.0
        length_offset: -1.0
        width_offset: 0.0
        nl: 15
        nw: 15

algo:
    type: MPPIIRLSpeedmaps
    params:
        mppi_itrs: 10
        batch_size: 8
        reg_coeff: 1.0e-08
        speed_coeff: 0.01
        grad_clip: 1.0

dataset:
    type: MaxEntIRLDataset
    params:
        bag_fp: /home/atv/Desktop/datasets/yamaha_maxent_irl/torch_train_h75
        preprocess_fp: /home/atv/Desktop/datasets/yamaha_maxent_irl/torch_train_h75
        map_features_topic: /local_gridmap
        odom_topic: /integrated_to_init
        image_topic: /multisense/left/image_rect_color
        horizon: 75
        feature_keys:
            - height_low
            - height_mean
            - height_high
            - height_max
            - diff
            - terrain
            - terrain_slope
            - roughness
            - SVD1
            - SVD2
            - SVD3
            - unknown
#            - ego_speed

network:
    type: ResnetCostmapSpeedmapCNNEnsemble2
    params:
        ensemble_dim: 4
        hidden_channels: [128, 128, 128]
        hidden_activation: relu
        activation_type: none
        activation_scale: 1.0
        dropout: 0.0

netopt:
    type: AdamW
    params: {}

mpc:
    mpc_fp: /home/atv/physics_atv_ws/src/perception/maxent_irl_maps/configs/mpc/throttle_mppi.yaml

metrics:
