experiment:
    save_to: /home/striest/Desktop/experiments/warthog_maxent_irl
    name: forest_cnn_deeper
    device: cuda
    epochs: 50
    steps_per_epoch: 10
    save_every: 1

algo:
    type: MPPIIRL
    params:
        mppi_itrs: 10
        batch_size: 16

dataset:
    type: MaxEntIRLDataset
    params:
        bag_fp: /home/striest/Desktop/datasets/warthog_maxent_irl/rosbags_train
        preprocess_fp: /home/striest/Desktop/datasets/warthog_maxent_irl/torch_train
        map_features_topic: /local_gridmap
        odom_topic: /warty/odom
        image_topic: /warty/stereo_left/image_rect_color/compressed
        horizon: 100

network:
    type: ResnetCostMapCNN
    params:
        hidden_channels: [64, 64, 64]

netopt:
    type: Adam
    params: {}

cost_function:
    type: WaypointCostMapCostFunction
    params:
        unknown_cost: 0.
        goal_cost: 50.0

model:
    type: SkidSteer
    params:
        v_lim: [-2.0, 2.0]
        w_lim: [-1.5, 1.5]

trajopt:
    type: MPPI
    params: 
        num_samples: 2048
        control_params:
            sys_noise: [2.0, 0.2]
            temperature: 1.0
            use_ou: False

metrics:
