experiment:
    save_to: /home/striest/Desktop/experiments/yamaha_maxent_irl
    name: resnet_fast_data
    device: cuda
    epochs: 50
    steps_per_epoch: 10
    save_every: 1

algo:
    type: MPPIIRL
    params:
        mppi_itrs: 10
        batch_size: 8

dataset:
    type: MaxEntIRLDataset
    params:
        bag_fp: /home/striest/Desktop/datasets/yamaha_maxent_irl/big_gridmaps/rosbags_train
        preprocess_fp: /home/striest/Desktop/datasets/yamaha_maxent_irl/big_gridmaps/torch_train
        map_features_topic: /local_gridmap
        odom_topic: /integrated_to_init
        image_topic: /multisense/left/image_rect_color
        horizon: 50

network:
    type: ResnetCostMapCNN
    params:
        hidden_channels: [64, 64, 64]
        activation_scale: 1.0

netopt:
    type: Adam
    params: {}

cost_function:
    type: WaypointCostMapCostFunction
    params:
        unknown_cost: 0.
        goal_cost: 30.0

model:
    type: SteerSetpointKBM
    params:
        L: 3.0
        v_target_lim: [0.0, 15.0]
        steer_lim: [-0.5, 0.5]
        steer_rate_lim: 0.5
        v_Kp: 1.0
        w_Kp: 10.0

trajopt:
    type: MPPI
    params: 
        num_samples: 2048
        control_params:
            sys_noise: [2.0, 0.2]
            temperature: 1.0
            use_ou: False

metrics:
