experiment:
    save_to: /home/striest/Desktop/experiments/yamaha_maxent_irl
    name: bigger_net_with_reg
    device: cuda
    epochs: 200
    steps_per_epoch: 10
    save_every: 1

algo:
    type: MPPIIRL
    params:
        mppi_itrs: 10
        batch_size: 12
        reg_coeff: 0.001

dataset:
    type: MaxEntIRLDataset
    params:
        bag_fp: /home/striest/Desktop/datasets/yamaha_maxent_irl/big_gridmaps/rosbags_train
        preprocess_fp: /home/striest/Desktop/datasets/yamaha_maxent_irl/big_gridmaps/torch_train_h75
        map_features_topic: /local_gridmap
        odom_topic: /integrated_to_init
        image_topic: /multisense/left/image_rect_color
        horizon: 75

network:
    type: ResnetCostMapCNN
    params:
        hidden_channels: [128, 128]
        activation_type: exponential
        activation_scale: 1.0

netopt:
    type: Adam
    params: {}

cost_function:
    type: WaypointCostMapCostFunction
    params:
        unknown_cost: 0.
        goal_cost: 20.0

model:
    type: SteerSetpointKBM
    params:
        L: 3.0
        v_target_lim: [2.0, 15.0]
        steer_lim: [-0.5, 0.5]
        steer_rate_lim: 0.5
        v_Kp: 1.0
        w_Kp: 10.0

trajopt:
    type: MPPI
    params: 
        num_samples: 2048
        control_params:
            sys_noise: [5.0, 0.25]
            temperature: 0.1
            use_ou: True
            ou_alpha: 0.9
            ou_scale: 10.0
            d_ou_scale: 5.0

metrics:
