---
common:
    B: 1           #number of optimizations to run in parallel
    H: 75         #number of timesteps to roll out
    M: 2           #dim of action space
    dt: 0.1        #length of timestep
    device: cuda   #device to run on 
    compile: false  #whether to compile MPC (runs faster but takes ~1 min on setup)

model:
    type: SteerSetpointThrottleKBM
    args:
        L: 2.0
        throttle_lim: [0., 1.]
        steer_lim: [-0.52, 0.52]
        steer_rate_lim: 0.4

        #planar offset (in body frame) from odom to center of vehicle
        offset_to_center: [-2.2, 0.0]

sampling_strategies:
    sampling_strategies:
    strategies:
        - type: ActionLibrary
          label: action_library
          args:
            K: 441
            path: "/home/tartandriver/tartandriver_ws/src/control/torch_mpc/data/action_libraries/yamaha_atv/H100_throttle_steer_unif.pt"

        - type: GaussianWalk
          label: gaussian_walk1
          args:
            K: 1024
            initial_distribution:
                type: gaussian
                scale: [0.5, 0.0]
            alpha: [0.0, 0.0]   #low-pass on noise
            scale: [0.01, 0.01]  #sample scale on change of noise

        - type: GaussianWalk
          label: gaussian_walk2
          args:
            K: 512
            initial_distribution:
                type: gaussian
                scale: [0.5, 0.0]
            alpha: [0.0, 0.0]   #low-pass on noise
            scale: [0.005, 0.005]  #sample scale on change of noise

        - type: GaussianWalk
          label: gaussian_walk3
          args:
            K: 512
            initial_distribution:
                type: gaussian
                scale: [0.5, 0.0]
            alpha: [0.0, 0.0]   #low-pass on noise
            scale: [0.0025, 0.0025]  #sample scale on change of noise

cost_function:
    footprint:
        key: footprint_trajs
        args:
          length: 4.0
          width: 2.0
          
          #displacement to get to the center of the footprint from the center of the rear axle
          length_offset: 1.2
          width_offset: 0.0

          nl: 11
          nw: 5

    terms:
        - type: FootprintCostmapProjection
          weight: 1.0
          label: costmap_projection
          args:
            costmap_key: local_navmap #should match the name in the ros section
            feature_key: cost #should match a feature key in the ros section
            footprint_key: footprint_trajs
            
        - type: EuclideanDistanceToGoal
          label: dist_to_goal
          goal_key: waypoints
          weight: 5.0
          args:

# this defines what the MPPI node subscribes to
ros:
    max_age: 2.

    topics:
      - name: state
        topic: /superodometry/integrated_to_init
        type: OdomRBState
        args: {}

      - name: steer_angle
        topic: /talon/current_position
        type: Float32
        args: {}

      - name: pitch
        topic: /gps_pitch
        type: Float32
        args: {}

      - name: local_navmap
        topic: /local_navmap
        type: BEVGrid
        args: {}

      - name: waypoints
        topic: /next_waypoints/odom
        type: GoalArray
        args: {}


update_rule:
    type: MPPI
    args:
        temperature: 0.1
        
recovery_behavior: []
