experiment:
    save_to: /home/offroad/Desktop/experiments/yamaha_maxent_irl/random_stuff
    name: 1layer_relu
    device: cuda
    epochs: 50
    steps_per_epoch: -1
    save_every: 1

algo:
    type: MPPIIRLSpeedmaps
    params:
        mppi_itrs: 10
        batch_size: 12
#        reg_coeff: 1.0e-07
        reg_coeff: 0.0
        speed_coeff: 0.0

dataset:
    type: MaxEntIRLDataset
    params:
        bag_fp: /home/offroad/Desktop/datasets/yamaha_maxent_irl/big_gridmaps/rosbags_train
        preprocess_fp: /home/offroad/Desktop/datasets/yamaha_maxent_irl/big_gridmaps/torch_train_h75
        map_features_topic: /local_gridmap
        odom_topic: /integrated_to_init
        image_topic: /multisense/left/image_rect_color
        horizon: 75

network:
    type: ResnetCostmapSpeedmapCNNEnsemble2
    params:
        ensemble_dim: 16
        hidden_channels: [32, ]
        hidden_activation: tanh
        activation_type: relu
        activation_scale: 1.0
        dropout: 0.2

netopt:
    type: Adam
    params: {}

cost_function:
    type: BatchMultiWaypointCostMapCostFunction
    params:
        unknown_cost: 0.
        goal_cost: 20.0

model:
    type: SteerSetpointKBM
    params:
        L: 3.0
        v_target_lim: [2.0, 15.0]
        steer_lim: [-0.5, 0.5]
        steer_rate_lim: 0.5
        v_Kp: 1.0
        w_Kp: 10.0

trajopt:
    type: BatchMPPI
    params: 
        num_samples: 2048
        control_params:
            sys_noise: [5.0, 0.25]
            temperature: 0.1
            use_ou: True
            ou_alpha: 0.9
            ou_scale: 10.0
            d_ou_scale: 5.0

metrics:
