experiment:
    save_to: /home/physics_atv/workspace/experiments/yamaha_irl_dino/visual_ablations_25cm
    name: visual_ablations_geom
    device: cuda
    epochs: 5
    steps_per_epoch: -1
    save_every: 1

footprint:
    params:
        length: 4.0
        width: 2.0
        length_offset: -1.0
        width_offset: 0.0
        nl: 15
        nw: 15

algo:
    type: PlannerIRLSpeedmaps
    params:
        batch_size: 4
        reg_coeff: 1.0e-08
        speed_coeff: 1.0 #turn off speedmaps for now
        grad_clip: 1.0

dataset:
    type: MaxEntIRLDataset
    params:
        root_fp: /home/physics_atv/workspace/datasets/irl_postpostproc_multimap_highres/train
        device: cuda
        feature_keys:
            # geom
            - terrain
            - terrain_slope
            - diff
            - SVD1
            - SVD2
            - SVD3
            - roughness
            - unknown

network:
    type: ResnetCostmapCategoricalSpeedmapCNNEnsemble2
    params:
        ensemble_dim: 16
        speed_nbins: 15
        max_speed: 15.
        hidden_channels: [128, 128]
        hidden_activation: tanh
#        activation_type: addmin #planner needs nonnegative costs
        activation_type: exponential #planner needs nonnegative costs
        activation_scale: 1.0
        dropout: 0.0

netopt:
    type: Adam
    params: {}

solver:
    type: planner
    planner_fp: /home/physics_atv/physics_atv_ws/src/perception/maxent_irl_maps/configs/planner/planner_config_highres_costmaps.yaml

metrics:
