experiment:
    save_to: /home/physics_atv/workspace/experiments/alien_irl
    name: alien_irl_pp
    device: cuda
    epochs: 25
    steps_per_epoch: -1
    save_every: 1

footprint:
    params:
        length: 0.6
        width: 0.3
        length_offset: 0.0
        width_offset: 0.0
        nl: 15
        nw: 15

algo:
    type: PlannerIRLSpeedmaps
    params:
        batch_size: 8
        reg_coeff: 1.0e-08
        speed_coeff: 0.0 #turn off speedmaps for now
        grad_clip: 1.0

dataset:
    type: PreprocessPointpillarsDataset
    params:
        preprocess_fp: /home/physics_atv/workspace/datasets/alien_irl/pointpillars/train
        gridmap_type: gridmap #for nonlearned
#        gridmap_type: learned_gridmap #for learned

network:
#    type: LinearCostmapSpeedmapEnsemble2
#    params:
#        ensemble_dim: 4
#        activation_type: none
#        activation_scale: 1.0
#        dropout: 0.0

    type: ResnetCostmapSpeedmapCNNEnsemble2
    params:
        ensemble_dim: 4
        hidden_channels: [64, ]
        hidden_activation: tanh
        activation_type: addmin #planner needs nonnegative costs
        activation_scale: 1.0
        dropout: 0.0

netopt:
    type: Adam
    params: {}

solver:
    type: planner
    planner_fp: /home/physics_atv/physics_atv_ws/src/perception/maxent_irl_maps/configs/planner/alien_planner_config.yaml

metrics:
