primitives:
    L: 5.0
    linear_resolution: 1.0
    angular_discretization: 16
    angular_weight: 1.
    maxdist: 5.0

state_lattice:
    length_x: 100.
    length_y: 100.
    origin: [-50., -50.]

costmap:
    length_x: 100.
    length_y: 100.
    resolution: 0.5
    origin: [-50., -50.]
