primitives:
    L: 3.0
    linear_resolution: 1.0
    angular_discretization: 16
    angular_weight: 1.
    maxdist: 3.5

state_lattice:
    length_x: 120.
    length_y: 120.
    origin: [-60., -60.]

costmap:
    length_x: 120.
    length_y: 120.
    resolution: 0.25
    origin: [-60., -60.]
