experiment:
    save_to: /home/tartandriver/workspace/experiments/yamaha_irl_dino/
    name: irl_cradio_siglip
    device: cuda
    epochs: 10
    steps_per_epoch: -1
    save_every: 1

footprint:
    params:
        length: 4.0
        width: 2.0
          
        #displacement to get to the center of the footprint from the center of the rear axle
        length_offset: 1.2
        width_offset: 0.0
        
        nl: 25
        nw: 15

algo:
    type: MPPIIRLSpeedmaps
    params:
        batch_size: 4
        reg_coeff: 0.0000001
        # reg_coeff: 0.0
        speed_coeff: 1.0 #turn off speedmaps for now
        grad_clip: 10.0

dataset:
    type: MaxEntIRLDataset
    params:
        root_fp: /media/striest/aaa/2025_irl/train
        device: cuda
        feature_keys:
            # VFM
            - c-radio_v3-b_siglip2_0
            - c-radio_v3-b_siglip2_1
            - c-radio_v3-b_siglip2_2
            - c-radio_v3-b_siglip2_3
            - c-radio_v3-b_siglip2_4
            - c-radio_v3-b_siglip2_5
            - c-radio_v3-b_siglip2_6
            - c-radio_v3-b_siglip2_7
            - c-radio_v3-b_siglip2_8
            - c-radio_v3-b_siglip2_9
            - c-radio_v3-b_siglip2_10
            - c-radio_v3-b_siglip2_11
            - c-radio_v3-b_siglip2_12
            - c-radio_v3-b_siglip2_13
            - c-radio_v3-b_siglip2_14
            - c-radio_v3-b_siglip2_15

            # geom
            # - min_elevation
            # - max_elevation
            - num_voxels
            # - terrain
            - slope
            - diff
            - min_elevation_filtered_inflated_mask

network:
    type: ResnetCategorical
    params:
        speed_nbins: 15
        max_speed: 15.
        cost_nbins: 20
        max_cost: 4.
        hidden_channels: [128,]
        hidden_activation: tanh
        hidden_kernel_size: 5
        dropout: 0.0

netopt:
    type: Adam
    params: {}

solver:
    type: mpc
    mpc_fp: /home/tartandriver/tartandriver_ws/src/planning/maxent_irl_maps/config/mpc/throttle_mppi.yaml

metrics:
